### PR TITLE
Quad generator

### PR DESCRIPTION
**Pull request by davidbirchwork**
QuadTree generator microservice
Milestone 1 - new service building 
Milestone 2 - specialise to networks
Milestone 3 - import quadtree code and convert to .netcore
Milestone 4 - wire up processing
Milestone 5 - add API to query

### CODE REVIEW

**Comment by miguems** [comment]
Is all of it necessary? Maybe David can prune inherited features that are not needed within OVE.

**Comment by davidbirchwork** [comment]
@miguems commits below pruned much of the inherited poor code 
98acd81
d42c920 
4daac6d 
Further pruning will be possible in later milestones once integration with Ove-networks is functional 

@senakafdo happy to walk you through the code later today

**Comment by miguems** [comment]
Cool! Which milestone is this? 3? Can't integration with ove-networks happen in an integration branch away from master? As you know I am not incliden to populate master with commits that contain unpolished code. But I would like to known others opinion (@senakafdo , @jamesscottbrown , @oserban )

**Comment by davidbirchwork** [comment]
@miguems as we agreed in the previous PR Discussion, we would do PR's by milestone to avoid colossal PR's . This is the first 5 milestones for this service. 

by all means we can keep a Dev branch and a clean Master as we did in gdo-fw

**Comment by senakafdo** [comment]
@miguems, @davidbirchwork, I need to get one critical question answered before we can decide whether this approach works or not. That is based on how this implementation handles edges that is not within the same Quad. Sigma edges should have an existing source and target, so I'm interested to know the sparsification algorithm a bit better:

1. How souce Quad preserves the target nodes if an edge was to be rendered at all
2. How the intermediate Quads (ones that are in between source and destination Quads) have awareness of an edge that is being propagated through them
3. How the destination/target Quad ensures that the node with an incoming edge is always plotted

I have seen this work for a large number of nodes, but that example did not have any edges at all - but that therefore is also not a network.

@miguems in terms of branch, the PR is on QuadGenerator anyway, so there is really no issue here. I think your concern here is that the entire piece of work needs to be completed before it is contributed to master? And that batches of commits into the QuadGenerator would have had to be reviewed as well. If this is why you propose a seperate branch, I'm +1. If it is not, I'm just wondering.

**Comment by miguems** [comment]
@senakafdo @davidbirchwork my concern here is that this code is apparently (from my brief informal review) a dump from another repo, and then an adaptation to .netcore and code cleaning. While this approach of developing is ok (though prone to add much more code than necessary and inherit not-optimal designs), pushing all this commits into master, will populate master with a lot of unneccesary code that is not actually integrated with the rest of the contents (integration will be done at a later stage as per @davidbirchwork comment above).  My proposal here (and to any other app/module that is imported from another source) is to fully adapt this code to the ove conventions and then, merge it in master. Also, I would recommend squash merge, rather than fully merge.

Otherwise, for some commits, we have two independent "projects" in the same repo that don't fully work with each other until a future commit.

Please,  keep in mind that this is a fully public repo that we are intending to have a wide audience. We have to be extra careful with what is publicly commited to the public master branch (as it will be there potentially forever). This care is not only with passwords, hardcoded urls, and so; it is also with proprietary assets and code.

@senakafdo : Yes, that is my proposal. What I see is "davidbirchwork wants to merge 23 commits into master from QuadGenerator". Therefore, if approved, those 23 commits will be part of master history (even though for some of them, the integration with the ove project is none). I am advocating for those milestones to be PR and reviewed to another separate branch. Once the QuadTree module is fully functional and fully integrated, merge it to master .

**Comment by senakafdo** [comment]
Closing this PR, as it is now stale and we are moving to a new repo.

**Pull request closed without merging**
