### PR TITLE
Image Meta API and GUI CRUD via crossplatform Sqlite and Entity Framework

### PR DESCRIPTION
**Pull request by davidbirchwork**
Intention to replace sqlite DBContext with external SQL/Mongo as decided in due course. 

should run happily on mac - @senakafdo could you kindly test? - Acceptance test if you can CRUD

recommend sqlitebrowser.org utility should you need

### CODE REVIEW

**Comment by senakafdo** [comment]
CRUD was tested via UI. Didn't find any APIs. Below is what I observed.
- Create
  - File upload seems to work, though the files were uploaded under packages/ove-service-imagetiles/ (alongside DB) which doesn't seem to be right. Ideally they should be under the packages/ove-service-imagetiles/dist folder or else git and lerna are getting confused.
  - Name of the file can be anything, which is ok, but why has someone got to type it? Can't we simply take the name from the file that is being uploaded and set it as the default?
- Read: all ok here
- Update: fails (with a broken web page) and nothing happens
- Delete:
  - Record is deleted - that part of it is ok.
  - File is remaining in the filesystem, which doesn't seem to be ok.

@davidbirchwork did you test these yourself and if so did these work differently? I don't assume that there are any OS-specific issues because most of it seems to be working perfectly.

**Comment by davidbirchwork** [comment]
@senakafdo ah i see what has happened - Two more commits have snuck into this PR. 
I had assumed the PR was issued against a fixed head commit as in my local git gui client. All of the issues identified related to the final two commits which are a work in progress when i stopped due to fever. 

Sorry about this. 

My testing found no problems against 8af6a95 and the issues you identify are either on my todo list or  as i'd expect from the two extra commits. 

API is defined in ImageFileModelsController & the GUI is coded against it. For ease of consumption i will remove the antiforgery cookie system in a later commit 

shall we revert the final two commits and then merge?

**Comment by miguems** [comment]
@davidbirchwork @senakafdo , there is no rush in merging. Please, make sure that the code works as expected, it is properly tested and it is of high quality. We should avoid being fixing bugs in master in the next few days, or lacking essential functionality.

**Comment by miguems** [comment]
Precisely @davidbirchwork : PR to master is intended to promote code that improves what is already there, fixes a bug or add some new functionality. Not half-baked code, or patches here and there; that is precisely what prevents reviewing from being smooth. 

Feature-branch was the approach we used in the past with gdoFW and the one I was advocating; not sure why you changed your workflow here when it is now much easier to accomplish it due to the distributed nature of the project.

**Comment by davidbirchwork** [comment]
This service is being developed as a series of mile stones. Each milestone will be a pull request. 
This is the first milestone completed and provides significant new features - namely API, GUI, CRUD, SQLite and entity framework.

**Comment by senakafdo** [comment]
@davidbirchwork sure I'll test and merge. @miguems, I'm assuming that we are happy to merge feature milestone branches, :).

**Pull request merged**
