### PR TITLE
add some diagrams explaining OVE

### PR DESCRIPTION
**Pull request by jamesscottbrown**

### CODE REVIEW

**Comment by senakafdo** [comment]
@jamesscottbrown, this is far from complete right? Are we able to finish off all these kinds of images and add them in one go? If so they can well be contributions to the issue on OVE documentation.

**Comment by jamesscottbrown** [comment]
> this is far from complete, right

These are *most* of the key diagrams I wanted to add, but there are a few more (e.g., some sequence diagrams showing which components communicate with each other and how).

> Are we able to finish off all these kinds of images and add them in one go?

Yes, we could.

Unlike adding incomplete code, merging documentation that doesn't describe the full design doesn't break things, so isn't necessarily a problem. I'd sent the pull request so that master was as up-to-date as possible, but you can leave it open if you prefer.

**Comment by senakafdo** [comment]
> Unlike adding incomplete code, merging documentation that doesn't describe the full design doesn't break things, so isn't necessarily a problem. I'd sent the pull request so that master was as up-to-date as possible, but you can leave it open if you prefer.

Not really what I meant. If we link these images to the docs then they make sense, if we don't I was wonder why we should merge this PR right now, because it will not be seen by anyone anyway. Also, OTOH, I wanted to encourage you to spend sometime to put some basic docs around these images so that I can actually merge this PR. My intention was not to keep this waiting forever, :).

**Comment by senakafdo** [comment]
@jamesscottbrown, please provide a MD catalog explaining and embedding these images on the documentation pages. Even though it may be a temporary thing, it will give the readers an idea of what they are looking at.

**Comment by senakafdo** [comment]
@jamesscottbrown, please note that I'm delaying the merging of this PR. The idea is to complete all the requirements for 0.1, review the design thoroughly, fix any design limitations and then write the documentation accordingly. While this PR accurately captures the design the software as of now, it may have to change a bit based on the design review.

**Comment by jamesscottbrown** [comment]
Ok.

I've also spotted a problem with the SVG diagrams: they specify a ``font-family`` that is available by default on Mac OS, but not Linux, and the replacement font has a different size so that the relative position of ``<tspan>`` elements is wrong.

**Comment by senakafdo** [comment]
> Hopefully this initial draft will be helpful in conducting the design review.

Yes, it certainly helps.

**Pull request closed without merging**
