### PR TITLE
Updated .net Skeleton:

### PR DESCRIPTION
**Pull request by davidbirchwork**
> move to .net core 2.1
> upgrade all dependencies
> move to kestrel
> supporting logging
> support Razor
> support MVC
> support EF

### CODE REVIEW

**Comment by miguems** [comment]
@davidbirchwork, we agreed that PR won't be merged by the same person issuing them. Next time, please, wait for someone else to review and approve it. You can suggest those reviewers yourself.
Thanks!

@senakafdo , is there a way in github to enforce this behavior and prevent this from happening in the future?

**Comment by jamesscottbrown** [comment]
Yes, it is possible to require reviews before merging:
https://help.github.com/articles/enabling-required-reviews-for-pull-requests/
Regards,

  James Scott-Brown
  james@jamesscottbrown.com


On Fri, Sep 7, 2018, at 6:31 PM, Miguel Molina-Solana wrote:
> @davidbirchwork[1], we agreed that PR won't be merged by the same
> person issuing them. Next time, please, wait for someone else to
> review and approve it. You can suggest those reviewers yourself.>  Thanks!


> @senakafdo[2] , is there a way in github to enforce this behavior and
> prevent this from happening in the future?> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[3], or mute the
> thread[4].

Links:

  1. https://github.com/davidbirchwork
  2. https://github.com/senakafdo
  3. https://github.com/dsi-icl/ove/pull/9#issuecomment-419511350

**Comment by davidbirchwork** [comment]
@miguems of course, this merge undertaken following discussion and agreement with @senakafdo before leaving on Friday

**Comment by senakafdo** [comment]
@miguems, @jamesscottbrown, @davidbirchwork, I have setup enforcement of review before PR merging.

This PR is fine, I reviewed it in retrospect - looks ok, but a few questions @davidbirchwork. Given that this first commit is at a "Hello World"-level, I assume you'd be fixing these in future commits:
1. Is the Error View Model as expected or auto-generated?
2. We seem to have unwanted launch settings.
3. The banner and favicon may not be required. If they were carried forward from another project, we cannot use it here since this is MIT licensed OSS.
4. There are some development-only settings in addition to the standard layout. Do we really need these?

Best Regards,
Senaka.

**Comment by davidbirchwork** [comment]
Thanks @senakafdo 

1. `ErrorViewModel ` is as expected, allows pretty printing of errors in corresponding `Error.cshtml`
2. Sure can remove but would rather keep both profiles, one offers a faster development experience, both use Kestrel behind the scenes. 
3. Good catch will remove 
4. These are used by IDE launch only could remove but same as 2.

**Comment by miguems** [comment]
Hi @senakafdo , 
why did you give green light for this PR to be issued and merged at such an early stage? Wouldn't it be better to only merge branches when their functionality is completed and tested? I am particularly keen on having a tidy master branch, and not using it as an integration branch for developers.

**Comment by senakafdo** [comment]
Hi @miguems,

I agree with your viewpoint and that is the standard development best practice in most OSS projects. However, since we are still at version 0.1.0 (milestone 1), I wasn't assuming that we should be enforcing this. However, once we have started deploying the code on our servers, which will happen early next week, the practice of 'PRs only' along with 'review then merge' will be strictly enforced.

I also plan to discuss with you and other team members on defining issue and PR templates, and also some contribution guidelines to maintain some order. These will be in line with OSS community standards, https://opensource.guide/.

Best Regards,
Senaka.

**Pull request merged**
